const KEY="duoliner_demo_db_v2";
function getDB(){return JSON.parse(localStorage.getItem(KEY)||'{"clientes":[],"pedidos":[],"pagos":[]}')}
function saveDB(db){localStorage.setItem(KEY,JSON.stringify(db))}
function money(n){return "Q"+Number(n||0).toLocaleString("es-GT",{minimumFractionDigits:2,maximumFractionDigits:2})}
function todayISO(){return new Date().toISOString().slice(0,10)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function daysSince(dateStr){const start=new Date(dateStr+"T00:00:00");return Math.max(0,Math.floor((new Date()-start)/86400000))}
function login(){const u=document.getElementById("user")?.value.trim();const p=document.getElementById("pass")?.value.trim();if(u==="admin"&&p==="1234"){localStorage.setItem("duoliner_session","ok");location.href="dashboard.html"}else{const e=document.getElementById("error");if(e)e.textContent="Usuario o contrasena incorrectos."}}
function checkAuth(){if(location.pathname.includes("dashboard")&&localStorage.getItem("duoliner_session")!=="ok")location.href="login.html"}
function logout(){localStorage.removeItem("duoliner_session");location.href="login.html"}
function showView(name,button){document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));const view=document.getElementById("view-"+name);if(view)view.classList.remove("hidden");document.querySelectorAll(".side-link").forEach(b=>b.classList.remove("active"));if(button)button.classList.add("active");renderAll()}
function clienteName(id){const db=getDB();return(db.clientes.find(c=>c.id===id)||{}).nombre||"Sin cliente"}
function pedidoName(id){const db=getDB();const p=db.pedidos.find(x=>x.id===id);return p?`${p.producto} - ${money(p.total)}`:"Sin pedido"}
function pagosDePedido(pedidoId){const db=getDB();return db.pagos.filter(p=>p.pedido_id===pedidoId).reduce((a,p)=>a+Number(p.monto||0),0)}
function saldoPedido(p){return Number(p.total||0)-pagosDePedido(p.id)}
function saldoCliente(clienteId){const db=getDB();return db.pedidos.filter(p=>p.cliente_id===clienteId&&p.estado!=="Cancelado").reduce((a,p)=>a+saldoPedido(p),0)}
function addCliente(){const db=getDB();const nombre=document.getElementById("clienteNombre").value.trim();if(!nombre)return alert("Ingresa el nombre del cliente.");db.clientes.push({id:uid(),nombre,nit:document.getElementById("clienteNit").value.trim(),telefono:document.getElementById("clienteTelefono").value.trim(),correo:document.getElementById("clienteCorreo").value.trim(),direccion:document.getElementById("clienteDireccion").value.trim(),fecha:todayISO()});saveDB(db);["clienteNombre","clienteNit","clienteTelefono","clienteCorreo","clienteDireccion"].forEach(id=>document.getElementById(id).value="");renderAll()}
function deleteCliente(id){if(!confirm("Eliminar cliente? Tambien se eliminaran sus pedidos y pagos."))return;const db=getDB();db.clientes=db.clientes.filter(c=>c.id!==id);db.pedidos=db.pedidos.filter(p=>p.cliente_id!==id);db.pagos=db.pagos.filter(p=>p.cliente_id!==id);saveDB(db);renderAll()}
function addPedido(){const db=getDB();const cliente_id=document.getElementById("pedidoCliente").value;if(!cliente_id)return alert("Primero crea un cliente.");const producto=document.getElementById("pedidoProducto").value.trim();if(!producto)return alert("Ingresa producto o descripcion.");db.pedidos.push({id:uid(),cliente_id,fecha:todayISO(),producto,cantidad:Number(document.getElementById("pedidoCantidad").value||0),total:Number(document.getElementById("pedidoTotal").value||0),estado:document.getElementById("pedidoEstado").value});saveDB(db);["pedidoProducto","pedidoCantidad","pedidoTotal"].forEach(id=>document.getElementById(id).value="");renderAll()}
function updateEstado(id,estado){const db=getDB();const p=db.pedidos.find(x=>x.id===id);if(p)p.estado=estado;saveDB(db);renderAll()}
function deletePedido(id){if(!confirm("Eliminar pedido?"))return;const db=getDB();db.pedidos=db.pedidos.filter(p=>p.id!==id);db.pagos=db.pagos.filter(p=>p.pedido_id!==id);saveDB(db);renderAll()}
function addPago(){const db=getDB();const cliente_id=document.getElementById("pagoCliente").value;const pedido_id=document.getElementById("pagoPedido").value;const monto=Number(document.getElementById("pagoMonto").value||0);if(!cliente_id||!pedido_id||monto<=0)return alert("Selecciona cliente, pedido y monto.");db.pagos.push({id:uid(),cliente_id,pedido_id,fecha:todayISO(),monto,metodo:document.getElementById("pagoMetodo").value.trim(),referencia:document.getElementById("pagoReferencia").value.trim()});saveDB(db);["pagoMonto","pagoMetodo","pagoReferencia"].forEach(id=>document.getElementById(id).value="");renderAll()}
function deletePago(id){if(!confirm("Eliminar pago?"))return;const db=getDB();db.pagos=db.pagos.filter(p=>p.id!==id);saveDB(db);renderAll()}
function renderSelects(){const db=getDB();const opts=db.clientes.map(c=>`<option value="${c.id}">${c.nombre}</option>`).join("");["pedidoCliente","pagoCliente"].forEach(id=>{const el=document.getElementById(id);if(el)el.innerHTML=opts||'<option value="">Sin clientes</option>'});const pagoCliente=document.getElementById("pagoCliente");const clienteId=pagoCliente?pagoCliente.value:"";const pedidos=db.pedidos.filter(p=>!clienteId||p.cliente_id===clienteId);const pOpts=pedidos.map(p=>`<option value="${p.id}">${p.producto} - saldo ${money(saldoPedido(p))}</option>`).join("");const pagoPedido=document.getElementById("pagoPedido");if(pagoPedido)pagoPedido.innerHTML=pOpts||'<option value="">Sin pedidos</option>';if(pagoCliente&&!pagoCliente.dataset.bound){pagoCliente.dataset.bound="1";pagoCliente.addEventListener("change",renderSelects)}}
function renderTables(){const db=getDB();const tc=document.getElementById("tablaClientes");if(tc)tc.innerHTML=`<tr><th>Cliente</th><th>NIT</th><th>Telefono</th><th>Correo</th><th>Saldo</th><th></th></tr>${db.clientes.map(c=>`<tr><td>${c.nombre}</td><td>${c.nit||"-"}</td><td>${c.telefono||"-"}</td><td>${c.correo||"-"}</td><td>${money(saldoCliente(c.id))}</td><td><button class="small-btn danger-btn" onclick="deleteCliente('${c.id}')">Eliminar</button></td></tr>`).join("")}`;const pedidosRows=db.pedidos.map(p=>`<tr><td>${clienteName(p.cliente_id)}</td><td>${p.producto}</td><td>${p.cantidad}</td><td>${p.fecha}</td><td>${daysSince(p.fecha)} dias</td><td>${money(p.total)}</td><td>${money(saldoPedido(p))}</td><td><select onchange="updateEstado('${p.id}', this.value)">${["Nuevo","En proceso","Pendiente de pago","Entregado","Cancelado"].map(e=>`<option ${p.estado===e?"selected":""}>${e}</option>`).join("")}</select></td><td><button class="small-btn danger-btn" onclick="deletePedido('${p.id}')">Eliminar</button></td></tr>`).join("");const tp=document.getElementById("tablaPedidos");if(tp)tp.innerHTML=`<tr><th>Cliente</th><th>Pedido</th><th>Cantidad</th><th>Fecha</th><th>Dias</th><th>Total</th><th>Saldo</th><th>Estado</th><th></th></tr>${pedidosRows}`;const tr=document.getElementById("tablaRecientes");if(tr)tr.innerHTML=`<tr><th>Cliente</th><th>Pedido</th><th>Fecha</th><th>Dias</th><th>Saldo</th><th>Estado</th></tr>${db.pedidos.slice(-8).reverse().map(p=>`<tr><td>${clienteName(p.cliente_id)}</td><td>${p.producto}</td><td>${p.fecha}</td><td>${daysSince(p.fecha)} dias</td><td>${money(saldoPedido(p))}</td><td><span class="badge-state">${p.estado}</span></td></tr>`).join("")}`;const tpa=document.getElementById("tablaPagos");if(tpa)tpa.innerHTML=`<tr><th>Fecha</th><th>Cliente</th><th>Pedido</th><th>Monto</th><th>Metodo</th><th>Referencia</th><th></th></tr>${db.pagos.map(p=>`<tr><td>${p.fecha}</td><td>${clienteName(p.cliente_id)}</td><td>${pedidoName(p.pedido_id)}</td><td>${money(p.monto)}</td><td>${p.metodo||"-"}</td><td>${p.referencia||"-"}</td><td><button class="small-btn danger-btn" onclick="deletePago('${p.id}')">Eliminar</button></td></tr>`).join("")}`;const tcu=document.getElementById("tablaCuenta");if(tcu)tcu.innerHTML=`<tr><th>Cliente</th><th>Pedidos</th><th>Total facturado</th><th>Pagado</th><th>Saldo</th></tr>${db.clientes.map(c=>{const pedidos=db.pedidos.filter(p=>p.cliente_id===c.id&&p.estado!=="Cancelado");const total=pedidos.reduce((a,p)=>a+Number(p.total||0),0);const pagado=db.pagos.filter(p=>p.cliente_id===c.id).reduce((a,p)=>a+Number(p.monto||0),0);return`<tr><td>${c.nombre}</td><td>${pedidos.length}</td><td>${money(total)}</td><td>${money(pagado)}</td><td><b>${money(total-pagado)}</b></td></tr>`}).join("")}`}
function renderKPIs(){const db=getDB();const kc=document.getElementById("kpiClientes");if(!kc)return;const abiertos=db.pedidos.filter(p=>!["Entregado","Cancelado"].includes(p.estado)).length;const saldo=db.pedidos.filter(p=>p.estado!=="Cancelado").reduce((a,p)=>a+saldoPedido(p),0);const pagos=db.pagos.reduce((a,p)=>a+Number(p.monto||0),0);kc.textContent=db.clientes.length;document.getElementById("kpiPedidos").textContent=abiertos;document.getElementById("kpiSaldo").textContent=money(saldo);document.getElementById("kpiPagos").textContent=money(pagos)}
function renderAll(){renderSelects();renderTables();renderKPIs()}
function seedDemo(){const db={clientes:[{id:"c1",nombre:"Cliente Industrial ABC",nit:"1234567-8",telefono:"5555-1111",correo:"compras@abc.com",direccion:"Guatemala",fecha:todayISO()},{id:"c2",nombre:"Distribuidora Central",nit:"7654321-0",telefono:"5555-2222",correo:"ventas@central.com",direccion:"Mixco",fecha:todayISO()}],pedidos:[{id:"p1",cliente_id:"c1",fecha:"2026-05-20",producto:"Sello 45mm",cantidad:1000,total:2500,estado:"En proceso"},{id:"p2",cliente_id:"c2",fecha:"2026-05-24",producto:"Sello personalizado 63mm",cantidad:500,total:1850,estado:"Pendiente de pago"}],pagos:[{id:"pa1",cliente_id:"c1",pedido_id:"p1",fecha:"2026-05-22",monto:1000,metodo:"Transferencia",referencia:"TRX-001"}]};saveDB(db);renderAll()}
function initReveals(){const reveals=document.querySelectorAll(".reveal");const io=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add("show")})},{threshold:.15});reveals.forEach(el=>io.observe(el))}
checkAuth();document.addEventListener("DOMContentLoaded",()=>{initReveals();renderAll()});
